import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#fffaf0',
        'surface-soft': '#faf5e8',
        'surface-card': '#f5f0e0',
        'surface-strong': '#ebe6d6',
        'surface-dark': '#0a1a1a',
        'surface-dark-elevated': '#1a2a2a',
        ink: '#0a0a0a',
        'body-strong': '#1a1a1a',
        body: '#3a3a3a',
        muted: '#6a6a6a',
        'muted-soft': '#7a7a7a',
        hairline: '#e5e5e5',
        'hairline-soft': '#f0f0f0',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'on-dark-soft': '#a0a0a0',
        'brand-pink': '#ff4d8b',
        'brand-teal': '#1a3a3a',
        'brand-lavender': '#b8a4ed',
        'brand-peach': '#ffb084',
        'brand-ochre': '#e8b94a',
        'brand-mint': '#a4d4c5',
        'brand-coral': '#ff6b5a',
      },
      borderRadius: {
        xs: '6px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        pill: '9999px',
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1', letterSpacing: '-2.5px', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '1.05', letterSpacing: '-2px', fontWeight: '500' }],
        'display-md': ['40px', { lineHeight: '1.1', letterSpacing: '-1px', fontWeight: '500' }],
        'display-sm': ['32px', { lineHeight: '1.15', letterSpacing: '-0.5px', fontWeight: '500' }],
        'title-lg': ['24px', { lineHeight: '1.3', letterSpacing: '-0.3px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'caption-uppercase': ['12px', { lineHeight: '1.4', letterSpacing: '1.5px', fontWeight: '600' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0', fontWeight: '600' }],
        'nav-link': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
    },
  },
  plugins: [],
}
export default config
